name: Build Docker Image

on:
  push:
    branches:
      - main
      - develop
      - 'develop/**'

env:
  IMAGE_NAME: PocketBase

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file ./.docker/Dockerfile --tag $IMAGE_NAME